project:
  type: website

website:
  title: "Atenciones de Urgencia Chile"
  navbar:
    left:
      - href: index.qmd
        text: Pediatría
      - href: adults.qmd
        text: Adultos

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

